// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20250608053326_AlimentarTablaVilla")]
    partial class AlimentarTablaVilla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Superficie")
                        .HasColumnType("float");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "Piscina, WiFi, Desayuno incluido",
                            Detalle = "Villa con vista al mar",
                            FechaActualizacion = new DateTime(2025, 6, 8, 0, 33, 26, 494, DateTimeKind.Local).AddTicks(6346),
                            FechaCreacion = new DateTime(2025, 6, 8, 0, 33, 26, 494, DateTimeKind.Local).AddTicks(6360),
                            ImagenUrl = "https://example.com/villa1.jpg",
                            Nombre = "Villa Real",
                            Ocupantes = 4,
                            Superficie = 150.5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "Jacuzzi, Vista panorámica",
                            Detalle = "Villa en la montaña",
                            FechaActualizacion = new DateTime(2025, 6, 8, 0, 33, 26, 494, DateTimeKind.Local).AddTicks(6364),
                            FechaCreacion = new DateTime(2025, 6, 8, 0, 33, 26, 494, DateTimeKind.Local).AddTicks(6365),
                            ImagenUrl = "https://example.com/villa2.jpg",
                            Nombre = "Villa Luna",
                            Ocupantes = 6,
                            Superficie = 200.0,
                            Tarifa = 250.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
